name: LightAPI
main: ru.beykerykt.lightapi.LightAPI
version: 3.0.0-dev
description: Bukkit Library for create invisible light source
author: BeYkeRYkt
permissions:
  lightapi.updater:
    default: false