name: LightAPI
main: ru.beykerykt.lightapi.LightAPI
version: 2.0.0-exp
description: Bukkit Library for create invisible light source
author: BeYkeRYkt
permissions:
  lightapi.updater:
    default: false