name: LightAPI
main: ru.beykerykt.minecraft.lightapi.bukkit.impl.BukkitPlugin
version: ${SERVER_API}-${project.version} (build ${BUILD_NUMBER})
description: Bukkit library for create invisible light source
author: BeYkeRYkt
authors: [other contributors in GitHub]
website: https://github.com/BeYkeRYkt/LightAPI
commands:
   lightapi:
      description: Main command